RAF-SI-2023/Banka-3-Backend

user-service/pom.xml
user-service/src/main/java/rs/edu/raf/userservice/dto/LoginRequest.java
user-service/src/main/java/rs/edu/raf/userservice/dto/LoginUserDto.java
user-service/src/main/java/rs/edu/raf/userservice/dto/RegistrerUserDto.java
user-service/src/main/java/rs/edu/raf/userservice/model/Permission.java
user-service/src/main/java/rs/edu/raf/userservice/model/Role.java
user-service/src/main/java/rs/edu/raf/userservice/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/model/enums/PermissionName.java
user-service/src/main/java/rs/edu/raf/userservice/model/enums/RoleName.java
user-service/src/main/resources/application.properties

Kreiran model sa entitetima User, Permission, Role, proveriti many to many i da li je potreban @jsonignore

Bck 1 kreiranje user entiteta

---

user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/SwaggerConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/LoginRequest.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/RegistrerUserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/ForbiddenException.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/UserMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Permission.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Role.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/enums/PermissionName.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/enums/RoleName.java
user-service/src/main/java/rs/edu/raf/userservice/filters/JwtFilter.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/RoleRepository.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/UserRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/RoleService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserService.java
user-service/src/main/java/rs/edu/raf/userservice/utils/JwtUtil.java

Ovaj PR bi trebalo da postavi osnovne klase i pakete koje cemo koristiti u projektu.
Neke stvari koje su dodate:
* `bootstrap`, `configuration`, `controllers`, `domains`, `filters`, `repositories`, `services` i `utils` base paketi.

Bck 10 postavljanje inicijalnih paketa i klasa

---

user-service/pom.xml
user-service/src/main/java/rs/edu/raf/userservice/configuration/SwaggerConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/resources/application.properties

Dodati dependacy i konfiguracija za swagger, testirano, radi.

BCK-7 integracija swaggera

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java

Dodate CRUD operacije u UserController, ali su sve `zakomentarisane` dok se ne pushuje service

BCK-2 Kreiranje user rest contollera sa crud operacijama

---

user-service/pom.xml
user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java

Ovaj PR bi trebalo da popravi swagger verziju

Bck 15 popravka swagger dependency verzije

---

user-service/pom.xml
user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/PasswordEncryptConfig.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/SwaggerConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/CreateUserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/CustomException.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/ErrorDetails.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/NotFoundException.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/UserMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Permission.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Role.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/filters/JwtFilter.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/UserRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserService.java
user-service/src/main/java/rs/edu/raf/userservice/utils/JwtUtil.java
user-service/src/main/resources/application.properties

Ovaj PR bi trebalo da doda password encryption i da formatira sve klase u projektu

BCK-17 Dodavanje password encryptiona

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/EmployeeController.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java

Ovaj PR bi trebalo da uspostavi saradnju `EmployeeService` i `EmployeeController` klasa.

BCK-18 integracija employee servisa i employee kontrolera

---

user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/EmployeeController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/AuthenticationDetails.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/EmployeeDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/UserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Employee.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Role.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/filters/JwtFilter.java
user-service/src/main/java/rs/edu/raf/userservice/services/CustomDetailsService.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java
user-service/src/main/java/rs/edu/raf/userservice/utils/JwtUtil.java

Dodata podrska za login employee i user tipa korisnika.

BCK-19 integracija logina za employee i user tipove korisnika

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/ForbiddenException.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserServiceInterface.java

BCK 6 Kreriranje Exception

---

user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/EmployeeController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/AuthenticationDetails.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/EmployeeDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/UserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/login/LoginResponse.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Employee.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Permission.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Role.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/enums/RoleName.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java
user-service/src/main/java/rs/edu/raf/userservice/utils/JwtUtil.java

Ovaj PR bi trebalo da ispravi relacije izmedju entiteta u bazi i da ispravno podesi stvari koje se smestaju u jwt

BCK-21 optimizacija jwt tokena i dodavanje permisija na metode

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/EmployeeController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/PermissionController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/RoleController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/employee/EmployeeCreateDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/employee/EmployeeDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/employee/EmployeeUpdateDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/user/CreateUserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/user/UpdateUserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/user/UserDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/UserMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Permission.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Role.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/EmployeeRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java
user-service/src/main/java/rs/edu/raf/userservice/services/PermissionService.java
user-service/src/main/java/rs/edu/raf/userservice/services/RoleService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserServiceInterface.java
user-service/src/main/java/rs/edu/raf/userservice/utils/JwtUtil.java
user-service/src/test/java/rs/edu/raf/userservice/EmployeeServiceUnitTests.java

Ovaj PR bi trebalo da doda permission i role repozitorijume servise i kontrolere

BCK-22 dodavanje permission i role repo controller i service

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/EmployeeController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/employee/EmployeeUpdateDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/EmployeeMapper.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java

Ovaj PR bi trebalo da doda employeeMapper klasu

BCK-23 Dodavanje employee mapper

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/EmployeeController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/ForbiddenException.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/GlobalExceptionHandler.java
user-service/src/main/java/rs/edu/raf/userservice/domains/exceptions/NotFoundException.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/EmployeeRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java

Ovaj PR bi trebalo da dopuni konfiguraciju exceptiona i da doda search funkcionalnost nad employee entitetima.

BCK 25 Konfiguracija exceptiona

---

user-service/src/main/java/rs/edu/raf/userservice/configuration/SwaggerConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/UserController.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/UserRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/EmployeeService.java
user-service/src/main/java/rs/edu/raf/userservice/services/PermissionService.java
user-service/src/main/java/rs/edu/raf/userservice/services/RoleService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserService.java
user-service/src/main/java/rs/edu/raf/userservice/services/UserServiceInterface.java
user-service/src/test/java/rs/edu/raf/userservice/UserServiceApplicationTests.java

Dodat search user-a i test metode

BCK-26 Search usera

---

user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/test/java/rs/edu/raf/userservice/EmployeeServiceUnitTests.java
user-service/src/test/java/rs/edu/raf/userservice/PermissionServiceUnitTests.java
user-service/src/test/java/rs/edu/raf/userservice/RoleServiceUnitTests.java
user-service/src/test/java/rs/edu/raf/userservice/UserServiceApplicationTests.java

Izmenjeni testovi i izmenjen gender u User modelu iz char u string

BCK-32 Ispravljeni testovi

---

user-service/src/main/java/rs/edu/raf/userservice/controllers/CreditController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/CreditRequestController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/credit/CreateCreditDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/credit/CreditDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/creditrequest/CreditRequestDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/CreditMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/CreditRequestMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Credit.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/CreditRequest.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/enums/CreditRequestStatus.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/CreditRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/CreditService.java

Kreirani Credit entitet, kontroler, servis, repozitorijum i dto-ovi. Implementirano odobravanje kredita (netestirano)

BCK-47 Odobravanje kredita od strane zaposlenog

---

bank-service/src/main/java/com/example/bankservice/controllers/CreditTransactionController.java
bank-service/src/main/java/com/example/bankservice/domains/dto/CreditTransactionDto.java
bank-service/src/main/java/com/example/bankservice/domains/mappers/CreditTransactionMapper.java
bank-service/src/main/java/com/example/bankservice/domains/model/CreditTransaction.java
bank-service/src/main/java/com/example/bankservice/repositories/CreditTransactionRepository.java
bank-service/src/main/java/com/example/bankservice/services/CreditTransactionService.java
bank-service/src/main/resources/application.properties
user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/CreditController.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/CreditRequestController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/credit/CreateCreditDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/credit/CreditDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/credit/CreditTransactionDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/creditrequest/CreditRequestCreateDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/creditrequest/CreditRequestDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/creditrequest/ProcessCreditRequestDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/CreditMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/CreditRequestMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Credit.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/CreditRequest.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/enums/CreditRequestStatus.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/CreditRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/CreditRequestService.java
user-service/src/main/java/rs/edu/raf/userservice/services/CreditService.java
user-service/src/main/java/rs/edu/raf/userservice/utils/BankServiceClient.java
user-service/src/main/resources/application.properties

Potrebno testirati cron job za otplatu mesecne rate kredita

Bck 47 odobravanje kredita od strane zaposlenog

---

user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
user-service/src/main/java/rs/edu/raf/userservice/controllers/ContactController.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/contact/ContactCreateDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/contact/ContactDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/dto/contact/ContactUpdateDto.java
user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/ContactMapper.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/Contact.java
user-service/src/main/java/rs/edu/raf/userservice/domains/model/User.java
user-service/src/main/java/rs/edu/raf/userservice/repositories/ContactRepository.java
user-service/src/main/java/rs/edu/raf/userservice/services/ContactService.java
user-service/src/test/java/rs/edu/raf/userservice/ContactServiceUnitTests.java

Bck 48 kontakti za placanje

---

exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureContractController.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyFutureCompanyDto.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/listing/FutureDto.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Future.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/FutureContract.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/FutureContractRepository.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/FutureContractService.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java

FutureContract dodat, izmene future-a da ima price

---

exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/StockController.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java

BCK-64-OTC-Company-Stocks

---

bank-service/src/main/java/com/example/bankservice/controller/CurrencyExchangeController.java
bank-service/src/main/java/com/example/bankservice/domain/model/CommissionFromCurrencyExchange.java
bank-service/src/main/java/com/example/bankservice/repository/CommissionFromCurrencyExhangeRepository.java
bank-service/src/main/java/com/example/bankservice/service/CommissionFromCurrencyExchangeService.java
bank-service/src/main/java/com/example/bankservice/service/CurrencyExchangeService.java
bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java

Implementirano dohvatanje ukupnog profita banke od menjacnice, potrebno je poslati sledeci poziv:
* `GET  localhost:8082/api/v1/currencyExchange`

BCK-69 Profit menjacnice

---

exchange-service/pom.xml
exchange-service/src/main/java/rs/edu/raf/exchangeservice/ExchangeServiceApplication.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/Banka4OtcController.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/FrontendOfferDto.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/MyOfferDto.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/MyStockDto.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/OfferDto.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Bank4Stock.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/MyOffer.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/Offer.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/OfferStatus.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/Bank4StockRepository.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/offerRepository/MyOfferRepository.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/offerRepository/OfferRepository.java
exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java

Uradjeno slanje i primanje ponuda sa nase strane, cekamo url od banke 4.

Bck 68 implementacija otc trgovine sa bankom 4
